### ISSUE TITLE
Damaged or incomplete

### ISSUE THREAD

**Issue by javydreamercsw** [carljmosca/netbeans-macos-bundle#1]
Ran the script and everything seemed to work, but when trying to open the app I saw this error.
<img width="417" alt="screen shot 2018-08-02 at 12 27 59 pm" src="https://user-images.githubusercontent.com/2817343/43600205-9c065204-964f-11e8-8dad-01fa6b9a3687.png">

It looked like this in the Applications Folder.
<img width="130" alt="screen shot 2018-08-02 at 12 29 01 pm" src="https://user-images.githubusercontent.com/2817343/43600232-aeeb8d58-964f-11e8-914e-8ac2e1289132.png">

**Comment by carljmosca** [comment]
Was this with the password being entered?

**Comment by javydreamercsw** [comment]
I had to enter my Mac password, I assume because is copying files on /Application folder.

**Comment by carljmosca** [comment]
You got it.  Thanks for the feedback.

**Comment by javydreamercsw** [comment]
I don't think this is addressed yet. You closed while I edited my previous reply since I misunderstood the question.

**Comment by javydreamercsw** [comment]
The app doesn't work for me after installation.

**Comment by carljmosca** [comment]
Ah, ok, sorry will take a look.

**Comment by carljmosca** [comment]
Info.plist permission issue.

**Comment by javydreamercsw** [comment]
Now it worked perfectly, thanks!
