### ISSUE TITLE
Missing Maven Java EE 

### ISSUE THREAD

**Issue by hannesa2** [carljmosca/netbeans-macos-bundle#15]
I get this, but under Tools->Plugins I don't find such a install candidate.
Any hints to solve this ?
<img width="544" alt="image" src="https://user-images.githubusercontent.com/3314607/46998394-b32d8c00-d122-11e8-845d-b5a8e358bbae.png">

**Comment by carljmosca** [comment]
Which version of NetBeans is this (just confirming)?

**Comment by hannesa2** [comment]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/3314607/47063054-e0894100-d1d9-11e8-967a-665b816c3161.png">

**Comment by alvint** [comment]
NetBeans 9 doesn't ship with Java EE support, but if you can install it from the NetBeans 8.2 plugin center. See [this blog post](https://blogs.apache.org/netbeans/entry/what-s-happened-to-my) for details.

In any case, it has nothing to do with the installer/this project.

**Comment by hannesa2** [comment]
Great, it helps me a lot, and of course it's not a issue of this installer. Thank you !
But anyway, Netbeans 9 makes more issues for me compared to the expected progress.

It seams all the developer are using Windows, as a Mac user you are to progressive. -sad-
