### ISSUE TITLE
NSSupportsAutomaticGraphicsSwitching has now effect

### ISSUE THREAD

**Issue by dyorgio** [carljmosca/netbeans-macos-bundle#17]
Sadly this Info.plist key is not working...
Probally because in the end a new java command is started to launch app.

The effect is a high usage of baterry on any macbook pro with onboard/discrete GPU auto switch.

**Comment by carljmosca** [comment]
Were you seeing the same issue with prior versions of NetBeans?

**Comment by dyorgio** [comment]
Yes :(, appears to be a old bug of NetBeans never solved.
I'm closing it beause needs to be fixed on NetBeans project.
(https://netbeans.org/bugzilla/show_bug.cgi?id=241957)
