### ISSUE TITLE
Not needed mv, ln, cp?

### ISSUE THREAD

**Issue by ulab** [carljmosca/netbeans-macos-bundle#22]
Hey Carl,

is there a specific reason for the mv, ln and cp commands in the script?

Only reason I see is the Info.plist file that references the targets. But shouldn't it be ok to modify the Info.plist instead?

Without any real knowledge about how those plist files work, I wonder if these changes would work instead:

```
<key>CFBundleExecutable</key>
<string>../Resources/netbeans/bin/netbeans</string>

<key>CFBundleIconFile</key>
<string>netbeans/nb/netbeans.icns</string>
```

I also wonder if the license information should be removed, since it's not an Oracle project anymore and if the `CFBundleIdentifier` needs to be changed (it references netbeans.org) and if the `CFBundleVersion` should be `9.0`.

Perhaps someone with more knowledge of the Info.plist file can give some tips here?

**Comment by carljmosca** [comment]
Thank you ulab.  I had some of those same thoughts initially but have not made time to go back and try that.  I did a bit of reading on the Info.plist magic but did not come away with a complete understanding.  

Yes, you're correct about the Oracle/netbeans.org references.  I think one version had a variable for the CFBundleVersion (I have been using this to install 9.x as well as 10.x).

Thank you for the help and feedback.

**Comment by ulab** [comment]
[It seems](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1) the `MacOS` folder is required and the main executable has to be in there.

> (Required) Contains the application’s standalone executable code. Typically, this directory contains only one binary file with your application’s main entry point and statically linked code. However, you may put other standalone executables (such as command-line tools) in this directory as well.

So changing `CFBundleExecutable` might not be enough / allowed. I am not sure if linking it is the proper way though ;)

**Comment by carljmosca** [comment]
I did play around with a bit and that sounds familiar now that you mention it...yes on the too much voodoo...almost as if they want it that way. :)
