### ISSUE TITLE
Netbeans 9 won't launch on MacOS v10.13.6

### ISSUE THREAD

**Issue by FEDevTP** [carljmosca/netbeans-macos-bundle#24]
Hi! I have High Sierra on my Mac and I can't launch NetBeans 9. When I try launching from launchpad nothing happens and I get no message, and when I try doing it from the .exe file it says that Mac cannot launch Windows apps. I've followed the instructions from the recommended video. The installation went smoothly, but it won't launch.
<img width="419" alt="screen shot 2018-12-13 at 15 07 48" src="https://user-images.githubusercontent.com/28805836/49945250-b8be0d00-feec-11e8-9490-a1035b1e69b5.png">

**Comment by carljmosca** [comment]
How did you install NetBeans?  That is, which of the two scripts did you run?  (The exe file is not intended for use on MacOS.)

**Comment by FEDevTP** [comment]
I downloaded the zip file, found the extracted folder in the terminal and entered ./install.sh, as shown in the video. It installed ok, but then it wouldn't launch.

**Comment by FEDevTP** [comment]
So, apparently, I'm completely clueless. It was Java. I got someone to take a look at it, and it was Java I lacked. I'm really sorry for bothering you.

**Comment by carljmosca** [comment]
It's no bother and he feedback is appreciated.  The install-custom.sh script does check for Java thanks to @ulab 

The original one you ran should do the same.  Thank you.

**Comment by Lore75BIT** [comment]
Ualb yes I confirm that, this is what drive me to uninstall Netbeans, install Java and then reinstall Netbeans.
