### ISSUE TITLE
tell users in readme that they need to set $JAVA_HOME in bash_profile

### ISSUE THREAD

**Issue by briansisney** [carljmosca/netbeans-macos-bundle#26]
$ vim .bash_profile 

export JAVA_HOME=$(/usr/libexec/java_home)

**Comment by carljmosca** [comment]
Are you certain this is a requirement?  I don't recall using a Mac w/o setting JAVA_HOME (I tend to do a lot from the command line with different Java versions so I set it a good bit).  However, unsetting it did not cause the script to fail on my computer.  I did not remove Java from my PATH however when doing the test.

**Comment by Polarisation** [comment]
In my case (first install on a new Mac) it was not a requirement to set JAVA_HOME.

**Comment by carljmosca** [comment]
Closing.
