### ISSUE TITLE
Fails to launch with no error message if Java is not installed

### ISSUE THREAD

**Issue by Polarisation** [carljmosca/netbeans-macos-bundle#29]
MacOS 10.14.3, NetBeans 10.

After installing with the script, I opened NetBeans. It quit without an error message. In system.log I found:

```
com.apple.xpc.launchd[1] (org.netbeans.ide.baseide.10.6528[2722]): Service exited with abnormal code: 2
```

The problem seems to have been that I had not installed Java in advance. After installing JDK 11 from Oracle, it launched fine... but it was not obvious.

It would be helpful to add a warning message in this case to tell the user that they must install the JDK (or perhaps a Java runtime will suffice?)

**Comment by ulab** [comment]
Did you use the ./install-custom.sh script? That one shows a message that you need java ("Please note that you need to install java to run Netbeans.")

@carljmosca May I suggest to make it more clear that the install-custom.sh is the recommended script?

**Comment by Polarisation** [comment]
No I used ./install.sh

There may have been a non-fatal warning about missing Java at install time, but if there was I missed it and only realised there was a problem when trying to open the app.

**Comment by carljmosca** [comment]
There is now only one install script as install-custom.sh has replaced install.sh.  Closing.
