### ISSUE TITLE
Improvement: The link could be made relative

### ISSUE THREAD

**Issue by lamski** [carljmosca/netbeans-macos-bundle#3]
Hi,

Played around with the script and it produced a working MacOS app in the /Applications folder. However, the app would not work if moved to a different folder. This is because the link to `Contents/MacOS/netbeans` is the absolute path. The link could be changed to a relative path so that the app works anywhere. You can compare the link to the Netbeans 8.2 link: `../Resources/NetBeans/bin/netbeans`

Regards,
Leo

**Comment by carljmosca** [comment]
Good call, thank you Leo.  Please test when you have a chance.

**Comment by lamski** [comment]
Hi Carl,

The relative sym-link is working just fine. I see you've reverted the change.
Using an absolute path for the sym-link would make the app not work if it's moved to a different directory afterwards. However, this is might be a rage case since people rarely move apps. But if they do, the app would not work.

Regards,
Leo

**Comment by carljmosca** [comment]
Sorry, I was confused with another issue which turned out not to be an issue.  In the meantime, there's a new script which supports an installation location.

For example:

./install-custom.sh --install-dir /Users/Me --non-root-install

**Comment by carljmosca** [comment]
Please test the original script when you have a chance.  I have added back the symbolic link.  Thank you.

**Comment by lamski** [comment]
Performed the following tests:
1. Executed the updated install.sh - /Applications/NetBeans/NetBeans 9.app launches properly.
2. Moved the app to my user directory - the NetBeans 9.app still launches properly.
