### ISSUE TITLE
Correct download path is http://archive.apache.org/dist/

### ISSUE THREAD

**Issue by rafaelpalacios** [carljmosca/netbeans-macos-bundle#30]
Edit install.sh and use
http://archive.apache.org/dist/
instead of
http://apache.osuosl.org/

Therefore line 4 should look like this:
NETBEANS_URI=${NETBEANS_URI:-http://archive.apache.org/dist/incubator/netbeans/incubating-netbeans/incubating-10.0/incubating-netbeans-10.0-bin.zip}

**Comment by carljmosca** [comment]
I was under the impression that nearby mirror sites should be used and not apach.org.  Is this incorrect?

What would be appreciated is a small piece of code (I assume available) to find the closest mirror.
