### ISSUE TITLE
Info.plist not copied on Mojave

### ISSUE THREAD

**Issue by encrierdigital** [carljmosca/netbeans-macos-bundle#31]
Howdy,

First thanks for the job.

Info.plist has error on install : "sed Info.plist no such file" or something like that, my terminale window is gone...

This result by an "Application is damaged" error.

Replacing by the one in the repository fix the issue, maybe some security issue with Mojave.

Best regards

**Comment by carljmosca** [comment]
Thank you for the feedback.  A couple of questions:

which script did you use?
did you add any optional parameters?

Take care,
Carl

**Comment by encrierdigital** [comment]
It was install.sh with no additional parameters.

Sadly, I closed the terminal before to send you this feedback, so I can't exactly remember the error message, sorry.

Best regards
François

**Comment by carljmosca** [comment]
Got it, thank you for the feedback.  It's probably time for me to replace the install script with the install-custom one.
