### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by capeflynn** [carljmosca/netbeans-macos-bundle#33]
Not able to install Netbeans 11 due to below error

Downloading http://mirrors.ocf.berkeley.edu/apache/incubator/netbeans/incubating-netbeans/incubating-11.0/incubating-netbeans-11.0-bin.zip...
######################################################################## 100.0%
Expected SHA512 checksum: 9d7fbe5c6bcf781fc1d3f8e2aee62db0435dd716c60dc73ef900ee2817473cc5b0a8e12c1453b7e57aedcece70cff778673a8cf563c1fa4eea816d9636955d4b
File SHA512 checksum:     706bf92e4a2eb22e599032ff28bcd615a96d27d0eb7d7e7f988c880712ff9b509c003ed05d0c534acf72d724fa8b1ac679b4a559072f63ee2cb2b410aa32c47d
Cleaning up...
Checksum mismatch! Exiting.

**Comment by capeflynn** [comment]
I worked around it by downloading Netbeans manually and then pointing to that downloaded file for installation. I submitted the issue, just so you would be aware in case it wasn't just me doing something wrong.

**Comment by carljmosca** [comment]
Unable to reproduce
