### ISSUE TITLE
Unable to start Netbeans 9

### ISSUE THREAD

**Issue by hh2k** [carljmosca/netbeans-macos-bundle#4]
Hi,

I've tried the script but was unable to start Netbeans 9 afterwards, I've attached the screenshots. Am I missing something?
![screen shot 2018-08-21 at 11 15 31](https://user-images.githubusercontent.com/771871/44392948-b138b980-a533-11e8-97f4-b94e00522161.png)
![screen shot 2018-08-21 at 11 15 37](https://user-images.githubusercontent.com/771871/44392949-b1d15000-a533-11e8-98a1-63723ffbfe3b.png)

I can start it if I go to /Applications/NetBeans/NetBeans 9.app/Contents/MacOS ./netbeans

**Comment by carljmosca** [comment]
I am sorry. Please try again.  I backed out a change which changed the symbolic link.

**Comment by hh2k** [comment]
Still not working for me. I noticed the Info.plist is empty, if that has anything to do with it.

**Comment by carljmosca** [comment]
Interesting...can you confirm that you are able to read the original Info.plist from the command line...perhaps a cat <Info.plist

**Comment by hh2k** [comment]
OK my bad it seems. I was only downloading the install script. I have both files now and it works. I did not notice the plist file. Maybe it could be downloaded from the script ?

**Comment by carljmosca** [comment]
Ah, interesting idea...had not thought of that.  Will get to it.  Thank you for the feedback.

**Comment by carljmosca** [comment]
opening including Info.plist in a new issue.
