### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by uchuugaka** [carljmosca/netbeans-macos-bundle#6]
Why does this have a GPL license in the files?
I have never seen a license note in an Info.plist file before, but also, why would a shell script have a license at all?

**Comment by carljmosca** [comment]
The Info.plist is from the 8.x version.  I believe it says "or" with respect to GPL/CDDL licenses and that the copyright notices should not be altered or removed.  The Info.plist list was added to the alternate script file after someone requested a version which did not require cloning or downloading the project.  Is there a problem with message being there?

**Comment by uchuugaka** [comment]
Sorry, legalese is not my strongest skill. I was in part surprised because I would not expect to even see GPL with Apache managed releases. The biggest problem though would potentially be with corporate legal departments which often more closely scrutinize use of GPL and CDDL licenses among others that corporate law teams tend to view as viral and risky. They tend to be comfortable with less restrictive licenses such as Apache, BSD, MIT and so on. It constrains what many folks can use in their work, unfortunately. It further constrains what they might be able to contribute back.

**Comment by carljmosca** [comment]
Thank you for the feedback.
