### ISSUE TITLE
You can’t open the application “NetBeans 9” because it may be damaged or incomplete.

### ISSUE THREAD

**Issue by gagarine** [carljmosca/netbeans-macos-bundle#7]
You can’t open the application “NetBeans 9” because it may be damaged or incomplete.
![screen shot 2018-09-07 at 10 55 18](https://user-images.githubusercontent.com/164074/45209188-98970600-b28c-11e8-9db8-60a8b63d1d7f.png)

This is what i have in the folder (4 level):

```
/A/N/NetBeans 9.app ❯❯❯ tree -L 4
.
└── Contents
    ├── Info.plist
    ├── MacOS
    │   └── netbeans -> ../Resources/NetBeans/bin/netbeans
    └── Resources
        ├── NetBeans
        │   ├── CREDITS.html
        │   ├── DEPENDENCIES
        │   ├── DISCLAIMER
        │   ├── LICENSE
        │   ├── NOTICE
        │   ├── README.html
        │   ├── apisupport
        │   ├── bin
        │   ├── etc
        │   ├── extide
        │   ├── harness
        │   ├── ide
        │   ├── java
        │   ├── javafx
        │   ├── licenses
        │   ├── nb
        │   ├── netbeans.css
        │   ├── platform
        │   ├── profiler
        │   └── websvccommon
        └── netbeans.icns

17 directories, 10 files
```

**Comment by gagarine** [comment]
Oh I see, it's because the plist is empty. Manually copying the .plist in the app bundle fix the problem.

Linked to #5

**Comment by carljmosca** [comment]
So just to confirm, did you git clone or download the project or just the installation script?

**Comment by gagarine** [comment]
I downloaded the full project from github (not git clone), unzip and then launch the script from the project folder.

**Comment by amatosg** [comment]
same happened to me, although the script downloaded the files

**Comment by carljmosca** [comment]
There are two installation scripts.  The newer alternative one, install-custom.sh, was designed such that the cloning or download (of this project) is not required.

**Comment by gagarine** [comment]
but I did download the full projet and install.sh did not works.

**Comment by gagarine** [comment]
Launching 
```
sed "s/NETBEANS_VERSION/$NETBEANS_VERSION/g" Info.plist > Info.plist.2
sudo mv Info.plist.2 "/Applications/NetBeans/NetBeans $NETBEANS_VERSION.app/Contents/Info.plist"
```
Directly in the terminal works. Strange.

**Comment by carljmosca** [comment]
Indeed it is.  I have not been able to reproduce that.  I will try on another Mac when I have a chance.  Does the alternate script work for you? (install-custom.sh)

**Comment by DraqueT** [comment]
I've moved info.plist into the proper place within the package, but am still unable to get past the "damaged or incomplete" message. Has anyone else had any luck here?

**Comment by carljmosca** [comment]
Which script did you use?

**Comment by DraqueT** [comment]
I used the newer one, install.sh, then copied the  info.plist file from the install directory over the empty one in the contents of the application. After that, I was still unable to open it.

**Comment by carljmosca** [comment]
please try the install-custom.sh

**Comment by DraqueT** [comment]
When I try the custom install, it explicitly gives me a permissions error when trying to copy over the info.plist file, then when I dive into the contents of the built application, it's just empty folders (shown below):
![image](https://user-images.githubusercontent.com/8284425/45758908-b3ef0300-bbf4-11e8-8927-9fb510a0fdfa.png)

Is there anything else that I might be missing here?

Also, appreciate the assistance.

**Comment by carljmosca** [comment]
[install.sh.txt](https://github.com/carljmosca/netbeans-macos-bundle/files/2397453/install.sh.txt)

I am sorry for the trouble.  First off, please confirm that you have rights to install (admin) and that you're prompted for a password during the installation.

Secondly, please try the attached install.sh script from the netbeans-macos-bundle project directory (you'll have to rename it and make it executable).

`
mv install.sh.txt installx.sh
chmod +x installx.sh
`

**Comment by DraqueT** [comment]
Alright, I seem to have found a workaround... If I open the netbeans shortcut file in the resources folder, I can run the IDE successfully. It's strange that I can't open it by double clicking on the application icon, as the info.plist file is correctly pointing to the internal shortcut.

Ah well. For anyone else who encounters this problem, this is a workaround for the moment.

**Comment by DraqueT** [comment]
@carljmosca Replied again before I saw that you had posted another install file! I will def check that one out and see if it makes things work better.

**Comment by waqa1988** [comment]
I think sometimes can't open because of JVM's version

`bogon:~ davi$ /Applications/NetBeans/NetBeans\ 9.app/Contents/Resources/NetBeans/bin/netbeans ; exit;
Unable to find any JVMs matching version "1.8.0+".
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openide/filesystems/FileUtil : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at org.netbeans.JarClassLoader.doLoadClass(JarClassLoader.java:286)
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:234)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:162)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.netbeans.core.startup.CLIOptions.cli(CLIOptions.java:134)
	at org.netbeans.core.startup.CLIOptions.cli(CLIOptions.java:73)
	at org.netbeans.CLIHandler.notifyHandlers(CLIHandler.java:209)
	at org.netbeans.CLIHandler.initialize(CLIHandler.java:494)
	at org.netbeans.CLIHandler.initialize(CLIHandler.java:359)
	at org.netbeans.MainImpl.execute(MainImpl.java:168)
	at org.netbeans.MainImpl.main(MainImpl.java:60)
	at org.netbeans.Main.main(Main.java:58)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...71 completed.

[进程已完成]`

**Comment by carljmosca** [comment]
Interesting, thank you.  I will give this a look.

**Comment by hannesa2** [comment]
Maybe someone helps it:

I was only to start it in ~/Application by 
`./install-custom.sh --non-root-install --install-dir ~/Applications` 
but there was no change to move it to `/Application` 

then I run into
> You can’t open the application “NetBeans 9” because it may be damaged or incomplete

**I made it work by**

`./install-custom.sh --install-dir /Applications`

The only minor remaining issue is the icon

<img width="164" alt="image" src="https://user-images.githubusercontent.com/3314607/46998591-44046780-d123-11e8-9ae2-ed2a99a6e5b5.png">
